version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    command: --lower_case_table_names=1
    env_file: ./.env
    ports:
      - "$MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
  app:
    build: .
    env_file: ./.env
    ports: 
      - "$NODEMAILER_PORT:$NODEMAILER_PORT"
      - "$BACKEND_PORT:$BACKEND_PORT"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql_db
    links:
      - mysql_db


volumes:
  db_data: